"""Email Digest Agent — formats and sends daily job digest."""
import logging
import smtplib
import ssl
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any

from jinja2 import Template

logger = logging.getLogger(__name__)

EMAIL_TEMPLATE = Template("""
<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; color: #333; }
  .header { background: #1a1a2e; color: white; padding: 20px; border-radius: 8px 8px 0 0; }
  .job-card { border: 1px solid #e0e0e0; border-radius: 8px; padding: 15px; margin: 10px 0; }
  .score-high { border-left: 4px solid #27ae60; }
  .score-med  { border-left: 4px solid #f39c12; }
  .score-tag  { display: inline-block; padding: 3px 10px; border-radius: 12px; font-size: 12px; font-weight: bold; }
  .tag-high   { background: #d5f5e3; color: #1e8449; }
  .tag-med    { background: #fef9e7; color: #b7770d; }
  .highlight  { background: #eaf4fb; padding: 2px 6px; border-radius: 4px; font-size: 12px; margin: 2px; display: inline-block; }
  .footer     { background: #f8f9fa; padding: 15px; border-radius: 0 0 8px 8px; font-size: 12px; color: #666; }
</style>
</head>
<body>
<div class="header">
  <h1>🤖 BaluAgent Daily Job Digest</h1>
  <p>{{ date }} · {{ total }} new matches · Top score: {{ top_score }}%</p>
</div>

{% for job in jobs %}
<div class="job-card {{ 'score-high' if job.match_score >= 0.85 else 'score-med' }}">
  <h3><a href="{{ job.url }}" style="color:#1a1a2e;text-decoration:none;">{{ job.jobtitle or job.title }}</a></h3>
  <p><strong>{{ job.company }}</strong> · {{ job.formattedLocation or 'Remote' }}</p>
  <span class="score-tag {{ 'tag-high' if job.match_score >= 0.85 else 'tag-med' }}">
    {{ (job.match_score * 100)|int }}% Match
  </span>
  <p style="font-size:13px;color:#555;">{{ job.match_reason }}</p>
  {% if job.highlights %}
  <p style="font-size:12px;">
    {% for h in job.highlights[:4] %}
    <span class="highlight">✓ {{ h }}</span>
    {% endfor %}
  </p>
  {% endif %}
  <p style="font-size:12px;color:#888;">{{ job.snippet or '' | truncate(200) }}</p>
</div>
{% endfor %}

<div class="footer">
  <p>Generated by BaluAgent · <a href="https://github.com/balakrishnav171/BaluAgent">GitHub</a></p>
  <p>Powered by LangChain + LangGraph · Scanned {{ total }} positions today</p>
</div>
</body>
</html>
""")


class EmailDigestAgent:
    """Formats job results and sends HTML email digest."""

    def __init__(
        self,
        smtp_host: str,
        smtp_port: int,
        smtp_user: str,
        smtp_password: str,
        recipient: str,
    ):
        self.smtp_host = smtp_host
        self.smtp_port = smtp_port
        self.smtp_user = smtp_user
        self.smtp_password = smtp_password
        self.recipient = recipient

    def _build_message(self, jobs: list[dict]) -> MIMEMultipart:
        top_score = max((j.get("match_score", 0) for j in jobs), default=0)
        html = EMAIL_TEMPLATE.render(
            date=datetime.utcnow().strftime("%A, %B %d %Y"),
            total=len(jobs),
            top_score=int(top_score * 100),
            jobs=jobs[:20],  # cap at 20 in email
        )
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"🤖 BaluAgent: {len(jobs)} Job Matches Today ({int(top_score*100)}% top)"
        msg["From"] = self.smtp_user
        msg["To"] = self.recipient
        msg.attach(MIMEText(html, "html"))
        return msg

    def send(self, jobs: list[dict]) -> bool:
        """Send digest email. Returns True on success."""
        if not jobs:
            logger.info("No jobs to send in digest")
            return False

        if not self.smtp_user or not self.smtp_password:
            logger.warning("SMTP credentials not configured — skipping email send")
            return False

        try:
            msg = self._build_message(jobs)
            context = ssl.create_default_context()
            with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
                server.ehlo()
                server.starttls(context=context)
                server.login(self.smtp_user, self.smtp_password)
                server.sendmail(self.smtp_user, self.recipient, msg.as_string())
            logger.info(f"Digest sent to {self.recipient} with {len(jobs)} jobs")
            return True
        except Exception as e:
            logger.error(f"Failed to send digest: {e}")
            return False

    def get_state(self) -> dict[str, Any]:
        return {"agent": "EmailDigestAgent", "recipient": self.recipient}
